RedHatInsights/insights-operator-cli

commands/clusters.go, commands/configurations.go, commands/profiles.go, commands/triggers.go, ioc.go, types/cluster.go, types/cluster_configuration.go, types/configuration_profile.go, types/trigger.go
=> Better parameter names

.travis.gocyclo.sh, .travis.gofmt.sh, .travis.golint.sh, .travis.govet.sh, .travis.yml, README.md
- Added gofmt
- Added go vet
- Added gocyclo
- Added golint
- Updated README
=> Configured CI

.travis.insightscontroller.sh, .travis.yml, tests/functional_test.go
the current tests are passed but I had to add `go build` to the stage although I think it should be build before...
=>  run controller in tests

.travis.yml
separated unit tests and functional tests
=> added stages to travis

commands/clusters.go, ioc.go
=> accept arguments to add cluster command

commands/clusters.go, ioc.go, restapi/api.go, restapi/api_impl.go
got this locally
```
> add cluster
clusterName: name
Error communicating with the service
Expected HTTP status 200 OK, 201 Created or 202 Accepted, got 404
```
=> removed ID from AddCluster

commands/authors_test.go, commands/common_test.go, commands/copyright_test.go, commands/help_test.go, commands/license_test.go, ioc_test.go
New unit tests has been added, just to show newcomers how it's possible to make them.
Fixes # (issue)
Just run `./test/sh` script and see results.
=> Unit tests first iteration

commands/clusters.go, commands/clusters_test.go, commands/rest_api_mock_empty_test.go, commands/rest_api_mock_errors_test.go, commands/rest_api_mock_test.go, tests/functional_test.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #31 
As usual, everything should be covered by `test.sh` script.
=> Basic commands unit tests

.travis.yml, README.md
Setup code coverage reporting on Codecov.io
Results are visible there: https://codecov.io/gh/RedHatInsights/insights-operator-cli
It's needed to check it there (on CI)
=> Codecov.io setup

commands/clusters.go, commands/clusters_test.go, commands/configurations.go, commands/configurations_test.go, commands/rest_api_mock_test.go, ioc.go, tests/functional_test.go
New unit tests for 'commands' + bunch of minor fixes
Just run `./test.sh` as usual
=> Unit tests for commands

commands/configurations.go, commands/configurations_test.go, ioc.go
Refactoring to be able to test non-interactive parts of the code (commands module)
Fixes #80 
New unit tests has been created, available through `./test.sh` command as usual.
=> Add cluster configuration command refactoring

commands/rest_api_mock_test.go, commands/triggers.go, commands/triggers_test.go
New unit tests for 'trigger' commands + minor refactoring
Fixes #88
As usual, please run `./test.sh`
=> Unit tests for triggers

commands/rest_api_mock_test.go
=> Simplify code

restapi/export_test.go, restapi/utils_test.go
New unit tests.
Run `./test.sh` as usual.
=> Unit tests for restapi utils

restapi/api_test.go
Unit tests for selected REST API methods.
Fixes #92
Use `./test.sh` as usual
=> API tests part 1

restapi/api_test.go, restapi/utils_test.go
Unit tests for the RestAPI implementation package.
Fixes #92 
Use `./test.sh` as usual
=> API tests part 2

restapi/api_test.go
Third bunch of unit tests for REST API.
Fixes # (issue)
Use `./test.sh` as usual.
=> Api tests part 3

export_test.go, ioc_test.go
Tests for `main` package should be in separate package.
Run `./test.sh` as usual.
=> Test for main in own package

functional_tests.sh, test.sh
Added shebangs to BASH scripts
=> Add shebangs to BASH scripts

commands/configurations_test.go, commands/profiles_test.go, restapi/api_test.go, restapi/utils.go, restapi/utils_test.go, tests/functional_test.go
Lot of missing error checks have been added.
It can be check on CI
=> Use error checks everywhere

goconst.sh, goerrcheck.sh, ineffassign.sh
New checks, not to be run on CI right now
N/A ATM
=> New checks on ci

DoD.md, PULL_REQUEST_TEMPLATE.md, README.md, gocyclo.sh, gofmt.sh, golint.sh, govet.sh
Bunch of minor issues (not planned for the sprint, so don't worry much)
Fixes # (issue)
- Documentation change
N/A
=> Minor improvements

restapi/api_impl.go
Fixes #112 #113 #115 
Please look at CI
=> Use net http method constants

.travis.yml, doc/generate_class_diagram.sh, functional_tests.sh, run.sh, run_on_ci.sh, test.sh
=> Missing licenses

.travis.yml, README.md, abcgo.sh
Incorporate ABC metrics
Fixes #120 
Please run `./abcgo.sh` on command line
=> Incorporate ABC metrics

.travis.yml
Run errcheck on CI
Fixes #103
Done on CI
=> Run errcheck on CI

.travis.yml
Incorporate ineffassign on CI
Fixes #104 
Done on CI
=> Incorporate ineffassign on CI

commands/configurations.go, commands/errors.go, commands/profiles.go
=> Fixed issue #109

commands/configurations.go, commands/errors.go, commands/profiles.go
=> Fixed issue #111

commands/clusters.go, commands/configurations.go, commands/errors.go, commands/profiles.go, commands/triggers.go
=> Fix issue #110

commands/configurations.go, commands/messages.go, commands/profiles.go
=> Fixed issue #130

commands/configurations.go, commands/messages.go, commands/profiles.go
=> Fix issue #129

commands/clusters.go, commands/configurations.go, commands/messages.go, commands/profiles.go, commands/triggers.go
=> Fix issue #116

ioc.go
=> Refactoring: fix issue #126

ioc.go
=> Refactoring: fix issue #114

commands/configurations.go, commands/messages.go, commands/profiles.go
=> Fixed issue #128

README.md, commands/configurations.go, commands/profiles.go
=> Refactoring + fixed issue #124

restapi/utils.go
Fixed G107 (CWE-88): Potential HTTP request made with variable url (Confidence: MEDIUM, Severity: MEDIUM)
Fixes #155
=> Fixed issue #155

commands/profiles.go
Fixes G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
Fixes #154
=> Fixed issue #154

.travis.yml, README.md, gosec.sh
Incorporate `gosec` checker into CI settings.
Fixes #119
=> Incorporate gosec

commands/configurations.go, commands/messages.go, commands/triggers.go
=> Fixed issue #127

ioc.go
=> Fixed issue #125

export_test.go, ioc.go, ioc_test.go
Refactoring reading configuraion
Fixes #97
=> Refactor reading configuration

govet.sh
Colorized output for `govet.sh` script.
Fixes #164
Can be seen on CI.
=> Colorized output of govet.sh script

README.md
=> Link to DoD

functional_tests.sh, tests/clusters_test.go, tests/common_commands_test.go, tests/functional_test.go
A bit of functional tests refactoring + documentation update + minor fixes.
Fixes #180
Done on CI automatically
=> Refactor functional tests add documentation

tests/configurations_test.go, tests/profiles_test.go, tests/triggers_test.go
=> Stub for new functional tests

DoD.md
Updaded Definition of Done
Fixes #173
N/A
=> Updated DoD

goconst.sh
Colorized output of goconst.sh script
Fixes #170 
Done on CI
=> Colorized output of goconst.sh script

gocyclo.sh
Colorized output of `gocyclo.sh` script
Fixes #169 
Done on CI
=> Colorized output of gocyclo.sh script

goerrcheck.sh
Colorized output of goerrcheck.sh script
Fixes #168
Done on CI
=> Colorized output of goerrcheck.sh script

golint.sh
Colorized output of `golint.sh` script
Fixes #166
Done on CI
=> Colorized output of golint.sh script

ineffassign.sh
Colorized output of `ineffassign.sh` script
Fixes #165
Done on CI
=> Colorized output of ineffassign.sh script

gofmt.sh
Colorized output of `gofmt.sh` script
Fixes #167
Done on CI
=> Colorized output of gofmt.sh script

types/cluster.go, types/cluster_configuration.go, types/cluster_configuration_test.go, types/cluster_test.go, types/common.go, types/common_test.go, types/configuration.go, types/configuration_profile.go, types/configuration_profile_test.go, types/configuration_test.go, types/trigger.go, types/trigger_test.go
Documentation for types module
Fixes #181
N/A
=> Documentation for types module

export_test.go, ioc.go, ioc_test.go
Documentation for the main module
Fixes #175
N/A
=> Documentation for the main module

configurations/README.md
Doc for `configuration` subdirectory
Fixes #177
N/A
=> Doc for configuration subdirectory

commands/clusters.go, commands/clusters_test.go, commands/configurations.go, commands/configurations_test.go, commands/copyright_test.go, commands/profiles.go, commands/profiles_test.go, commands/rest_api_mock_empty_test.go, commands/rest_api_mock_errors_test.go, commands/rest_api_mock_test.go, commands/triggers.go, commands/triggers_test.go
Ensure line length limit for commends in command package
N/A
=> Ensure line length limit for commends in command package

restapi/api.go, restapi/api_impl.go, restapi/api_test.go, restapi/export_test.go, restapi/utils_test.go
Ensure line length limit for commends in restapi package
N/A
=> Ensure line length limit for commends in restapi package

commands/authors.go, commands/clusters.go, commands/common.go, commands/configurations.go, commands/copyright.go, commands/errors.go, commands/help.go, commands/license.go, commands/messages.go, commands/profiles.go, commands/triggers.go
Updated comments for `commands` module
Fixes #176 
N/A
=> Updated comments for commands module

restapi/api.go, restapi/api_impl.go, restapi/config.go, restapi/utils.go
Updated comments for REST API module
Fixes #179
N/A
=> Updated comments for REST API module

docs/README.md, docs/index.md
=> Stub for GitHub pages

docs/Gemfile, docs/_config.yml
=> Style for GitHub pages

docs/index.md
Stub for links to package documentation
=> Stub for links to package documentation

abcgo.sh, goconst.sh, gocyclo.sh, goerrcheck.sh, golint.sh, gosec.sh, ineffassign.sh
Don't install any already installed go tools
Fixes #211 #212 #213 #214 #215 #216 #217
=> Dont install any already installed go tools

docs/packages/export_test.html, docs/packages/restapi/export_test.html, export_test.go, restapi/export_test.go
Comments for export test sources
N/A
=> Comments for export test sources

commands/commands.go, docs/packages/commands/commands.html
Package description for package `commands`
Fixes #224
N/A
=> Package description for package commands

commands/commands_test.go, docs/packages/commands/commands_test.html
Package description for package `commands_test`.
Fixes #230
N/A
=> Package description for package commands_test

docs/packages/restapi/restapi.html, restapi/restapi.go
Package description for package `restapi`.
Fixes #225
N/A
=> Package description for package restapi

docs/packages/restapi/restapi_test.html, restapi/restapi_test.go
Package description for package `restapi_test`.
Fixes #233 
N/A
=> Package description for package restapi test

docs/packages/types/types.html, types/types.go
Package description for package `types`
Fixes #226
N/A
=> Package description for package types

docs/packages/types/types_test.html, types/types_test.go
Package description for package `types_test`.
Fixes #236
N/A
=> Package description for package types_test

commands/authors.go, docs/packages/commands/authors.html
Comments for commands/authors.go source file
Fixes #238
N/A
=> Comments for commands/authors.go source file

commands/authors_test.go, docs/packages/commands/authors_test.html
Comments for commands/authors_test.go file
Fixes #239
N/A
=> Comments for commands/authors_test.go file

commands/clusters.go, docs/packages/commands/clusters.html
Comments for commands/clusters.go file
Fixes #240
N/A
=> Comments for commands/clusters.go file

commands/clusters_test.go, docs/packages/commands/clusters_test.html
Comments for commands/clusters_test.go file
Fixes #241 
N/A
=> Comments for commands/clusters_test.go file

commands/commands.go, docs/packages/commands/commands.html
List of sources in commands.go
N/A
=> List of sources in commands.go

commands/commands_test.go, docs/packages/commands/commands_test.html
List of sources in `commands_test.go`
N/A
=> List of sources in commands_test.go

commands/license_test.go, docs/packages/commands/license_test.html
Comments added into `license_test.go`
Fixes #258
N/A
=> Comments added into license_test.go

commands/help_test.go, docs/packages/commands/help_test.html
Comments added into `help_test.go`
Fixes #256
N/A
=> Comments added into help_test.go

commands/copyright_test.go, docs/packages/commands/copyright_test.html
Comments added into `copyright_test.go`
Fixes #253 
N/A
=> Comments added into copyright_test.go

commands/configurations_test.go
Some comments in `configurations_test.go`
N/A
=> Some comments in configurations_test.go

docs/packages/commands/configurations_test.html
Updated generated documentation a bit
N/A
=> Updated generated documentation a bit

commands/configurations_test.go, docs/packages/commands/configurations_test.html
Documentation for commands configurations test
Fixes #247 
N/A
=> Documentation for commands configurations test

commands/configurations.go, docs/packages/commands/configurations.html
Documentation for commands configurations
Fixes #246
N/A
=> Documentation for commands configurations

commands/common_test.go, docs/packages/commands/common_test.html
Documentation for `commands/common_test.go`
Fixes #245
N/A
=> Documentation for commands common test

commands/common.go, docs/packages/commands/common.html
Documentation for `commands/common.go`
Fixes #244
N/A
=> Documentation for `commands/common.go`

commands/commands_test.go, docs/packages/commands/commands_test.html
Documentation for `commands/commands_test.go`
Fixes #243
N/A
=> Documentation for `commands/commands_test.go`

commands/commands.go, docs/packages/commands/commands.html
Documentation for `commands/commands.go`
Fixes #242
N/A
=> Documentation for `commands/commands.go`

commands/copyright.go, docs/packages/commands/copyright.html
Documentation for `commands/copyright.go`
Fixes #252
N/A
=> Documentation for `commands/copyright.go`

commands/help.go, docs/packages/commands/help.html
Documentation for `commands/help.go`
Fixes #257
N/A
=> Documentation for `commands/help.go`

commands/profiles_test.go, docs/packages/commands/profiles_test.html
Documentation for `commands/profiles_test.go`
Fixes #261
N/A
=> Documentation for `commands/profiles_test.go`

commands/triggers_test.go, docs/packages/commands/triggers_test.html
Documentation for `commands/triggers_test.go`
Fixes #301
N/A
=> Documentation for `commands/triggers_test.go`

commands/triggers.go, docs/packages/commands/triggers.html
=> Fix issue 265

commands/authors.go, docs/packages/commands/authors.html
Fixed formatting in `authors.go`
Fixes # (issue)
N/A
=> Fixed formatting in `authors.go`

commands/authors_test.go, docs/packages/commands/authors_test.html
Fixed doc in `authors_test.go` (minor)
N/A
=> Fixed doc in `authors_test.go` (minor)

commands/clusters.go, docs/packages/commands/clusters.html
Minor doc update in `clusters.go`
N/A
=> Minor doc update in `clusters.go`

commands/clusters_test.go, docs/packages/commands/clusters_test.html
Minor doc update in `clusters_test.go`
N/A
=> Minor doc update in `clusters_test.go`

commands/commands.go, docs/packages/commands/commands.html
Minor update in `commands.go`
N/A
=> Minor update in `commands.go`

commands/authors.go, docs/packages/commands/authors.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/authors.go`
Fixes #277
N/A
=> Fix issue 277

commands/clusters.go, docs/packages/commands/clusters.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/clusters.go`
Fixes #279
N/A
=> Fix issue #279

commands/configurations.go, docs/packages/commands/configurations.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/clusters.go`
Fixes #2 
N/A
=> Fix issue #282

commands/common.go, docs/packages/commands/common.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/common.go`
Fixes #287
N/A
=> Fix issue #287

commands/license.go, docs/packages/commands/license.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/license.go`
Fixes #289
N/A
=> Fix issue #289

commands/errors.go, docs/packages/commands/errors.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/errors.go`
Fixes #290
N/A
=> Fix issue #290

commands/help.go, docs/packages/commands/help.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/help.go`
Fixes #291
N/A
=> Fix issue 291

commands/messages.go, docs/packages/commands/messages.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/messages.go`
Fixes #294
N/A
=> Fix issue #294

commands/authors_test.go, docs/packages/commands/authors_test.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/authors_test.go`
Fixes #278
N/A
=> Fix issue 278

commands/configurations_test.go, docs/packages/commands/configurations_test.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/configurations_test.go`
Fixes #283
N/A
=> Fix issue 283

commands/help_test.go, docs/packages/commands/help_test.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/help_test.go`
Fixes #292
N/A
=> Fix issue 292

commands/license_test.go, docs/packages/commands/license_test.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/license_test.go`
Fixes #293
N/A
=> Fix issue 293

commands/profiles_test.go, docs/packages/commands/profiles_test.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/profiles_test.go`
Fixes #296
N/A
=> Fix issue 296

commands/triggers_test.go, docs/packages/commands/triggers_test.html
Link in `triggers_test.go`
N/A
=> Link in `triggers_test.go`

commands/triggers.go, docs/packages/commands/triggers.html
Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/triggers.go`
Fixes #300
N/A
=> Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/triggers.go`

docs/packages/commands/authors_test.html, docs/packages/commands/clusters_test.html, docs/packages/commands/configurations_test.html, docs/packages/commands/copyright_test.html, docs/packages/commands/help_test.html, docs/packages/commands/license_test.html, docs/packages/commands/profiles_test.html, docs/packages/commands/rest_api_mock_empty_test.html, docs/packages/commands/rest_api_mock_errors_test.html, docs/packages/commands/rest_api_mock_test.html, docs/packages/commands/triggers_test.html
=> Updated generated doc

docs/packages/types/types.html, types/types.go, types/xxx
Add link to documentation generated for `types/types.go`
Fixes #362
N/A
=> Fix issue #362

docs/packages/types/trigger.html, types/trigger.go
Add link to documentation generated for `types/trigger.go`
Fixes #362
N/A
=> Fix issue 362

docs/packages/types/configuration.html, types/configuration.go
Add link to documentation generated for `types/configuration.go`
Fixes #356
N/A
=> Fix issue 356

docs/packages/types/common.html, types/common.go
Add link to documentation generated for `types/common.go`
Fixes #354
N/A
=> Fix issue 354

docs/packages/types/cluster.html, types/cluster.go
Add link to documentation generated for `types/cluster.go`
Fixes #352
N/A
=> Fix issue #352

docs/packages/types/cluster_configuration.html, types/cluster_configuration.go
Add link to documentation generated for `types/cluster_configuration.go`
Fixes #350
N/A
=> Fix issue #350

docs/packages/types/configuration_profile.html, types/configuration_profile.go
Add link to documentation generated for `types/configuration_profile.go`
Fixes #357
N/A
=> Fix issue #357

docs/packages/types/types_test.html, types/types_test.go
Add link to documentation generated for `types/types_test.go`
Fixes #363
N/A
=> Fix issue #363

docs/packages/types/trigger_test.html, types/trigger_test.go
Add link to documentation generated for `types/trigger_test.go`
Fixes #361
N/A
=> Fix issue #361

docs/packages/types/configuration_test.html, types/configuration_test.go
Add link to documentation generated for `types/configuration_test.go`
Fixes #359
N/A
=> Fix issue #359

docs/packages/types/common_test.html, types/common_test.go
Add link to documentation generated for `types/common_test.go`
Fixes #355 
N/A
=> Fix issue #355

docs/packages/types/cluster_test.html, types/cluster_test.go
Add link to documentation generated for `types/cluster_test.go`
Fixes #353
N/A
=> Fix issue #353

docs/packages/types/cluster_configuration_test.html, types/cluster_configuration_test.go
Add link to documentation generated for `types/cluster_configuration_test.go`
Fixes #351
N/A
=> Fix issue #351

.travis.yml
Added a new CI stage: build
Fixes #338
Done on CI
=> Added a new CI stage: build

docs/packages/commands/commands_test.html
=> Missing doc added

docs/packages/restapi/utils.html, restapi/utils.go
Fixes: the following string occured many times in sources: "Communication error with the server %v"
Fixes #147
N/A
=> Fixes: the following string occured many times in sources: "Communication error with the server %v"

commands/configurations.go, commands/messages.go, commands/profiles.go, commands/triggers.go, docs/packages/commands/configurations.html, docs/packages/commands/messages.html, docs/packages/commands/profiles.html, docs/packages/commands/triggers.html
Fixes: the following string occured many times in sources: "Not logged in"
Fixes #146
N/A
=> Fixes: the following string occured many times in sources: "Not logged in"

docs/packages/restapi/api.html, restapi/api.go
Added link to generated documentation for `restapi/api.go`
Fixes #379
N/A
=> Added link to generated documentation for `restapi/api.go`

docs/packages/restapi/api_impl.html, restapi/api_impl.go
Added link to generated documentation for `restapi/api_impl.go`
Fixes #380 
N/A
=> Added link to generated documentation for `restapi/api_impl.go`

docs/packages/restapi/config.html, restapi/config.go
Added link to generated documentation for `restapi/config.go`
Fixes #382
N/A
=> Added link to generated documentation for `restapi/config.go`

docs/packages/restapi/restapi.html, restapi/restapi.go
Added link to generated documentation for `restapi/restapi.go`
Fixes #384
N/A
=> Added link to generated documentation for `restapi/restapi.go`

docs/packages/tests/triggers_test.html, tests/triggers_test.go
=> Fix issue 393

docs/packages/tests/profiles_test.html, tests/profiles_test.go
=> Fix issue 392

docs/packages/tests/functional_test.html, tests/functional_test.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #391 
N/A
=> Fix issue 391

docs/packages/tests/configurations_test.html, tests/configurations_test.go
=> Fix issue 390

docs/packages/tests/common_commands_test.html, tests/common_commands_test.go
=> Fix issue 389

docs/packages/tests/clusters_test.html, tests/clusters_test.go
=> Fix issue 388

docs/packages/restapi/export_test.html, restapi/export_test.go
=> Fix issue 383

docs/packages/restapi/restapi_test.html, restapi/restapi_test.go
=> Fix issue 385

docs/packages/restapi/utils_test.html, restapi/utils_test.go
=> Fix issue 387

docs/packages/restapi/api_test.html, restapi/api_test.go
=> Fix issue 381

go.mod
Fix package name in `go.mod`
N/A
=> Fix package name in go.mod

README.md, go.mod
Bump-up Go version to supported version.
Fixes #430
- Update
N/A
=> Bump-up Go version

commands/triggers_test.go, docs/packages/commands/triggers_test.html
Docstrings update/addition.
Fixes #266
N/A
=> Fix issue 266

commands/rest_api_mock_test.go, docs/packages/commands/rest_api_mock_test.html
Docstrings update.
Fixes #264
N/A
=> Fix issue #264

commands/rest_api_mock_errors_test.go, docs/packages/commands/rest_api_mock_errors_test.html
Updated docstrings.
Fixes #263
N/A
=> Fix issue #263

commands/rest_api_mock_empty_test.go, docs/packages/commands/rest_api_mock_empty_test.html
Updated docstrings.
Fixes #262
N/A
=> Fix issue #262

commands/triggers_test.go, docs/packages/commands/triggers_test.html
Missing info in triggers_test.go
N/A
=> Missing info in triggers_test.go

commands/profiles_test.go, docs/packages/commands/profiles_test.html
Updated somments in profiles_test.go
N/A
=> Updated somments in profiles_test.go

commands/profiles.go, docs/packages/commands/profiles.html
Updated comments in profiles.go
Fixes #260
N/A
=> Updated comments in profiles.go

commands/messages.go, docs/packages/commands/messages.html
Updated comments in `messages.go`
Fixes #259
N/A
=> Updated comments in messages.go

commands/errors.go, docs/packages/commands/errors.html
Updated comments in `errors.go`
Fixes #254
N/A
=> Updated comments in errors.go

Makefile
Fixed issue #456
Fixes #456
N/A
=> Fixed issue #456

README.md
=> Generated TOC

commands/configurations.go, commands/messages.go, commands/profiles.go
Fix for issue #142 
Fixes #142
N/A
=> Fix issue #142

ioc.go
Replaced string literal by constant
Fixes #143
N/A
=> Replaced string literal by constant

commands/configurations.go, commands/messages.go, commands/triggers.go
Replace string literals by constant.
Fixes #148
N/A
=> Fix issue #148

commands/configurations.go, commands/messages.go, commands/triggers.go
Replaced string literals by constant.
Fixes #153
N/A
=> Fix issue #153

ioc.go
Replace empty `fallthrough`
N/A
=> Replace empty `fallthrough`

CONTRIBUTING.md
=> ToC in contributing doc

commands/profiles.go, gosec.sh, restapi/utils.go
Use latest gosec vetsion
Fixes #479 
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Use latest gosec vetsion

restapi/api_impl.go
=> Fixed issue #483

.github/workflows/golangci-lint.yml
Fixes golangci setup
Done on CI
=> Fixes golangci setup

commands/configurations.go, commands/profiles.go, commands/prompts.go
=> Fixed issue #151

ioc.go
Fixed issue #150
Fixes #150
Done on CI
=> Fixed issue #150

restapi/api_impl.go
Fixed issue #495
Fixes #495
Done on CI
=> Fixed issue #495

restapi/api_impl.go
Fixed issue #494
Fixes #494
Done on CI
=> Fixed issue #494

restapi/api_impl.go
Fixed issue #493
Fixes #493
Done on CI
=> Fixed issue #493

restapi/api_impl.go
Fixed issue #490
Fixes #490
Done on CI.
=> Fixed issue #490

commands/configurations.go, commands/profiles.go, restapi/api_impl.go, restapi/utils.go
Get rid of `ioutil` + other fixes
Fixes #484
Fixes #485
Fixes #486
Fixes #487
Fixes #488
Fixes #489
Fixes #491
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Get rid of ioutil + other fixes

commands/clusters.go, commands/clusters_test.go, commands/configurations.go, commands/configurations_test.go, commands/errors.go, commands/profiles.go, commands/profiles_test.go, commands/triggers.go, commands/triggers_test.go
Refactor messages
Fixes #508
Fixes #509
Fixes #510
Fixes #511
Fixes #512
Fixes #513
Fixes #514
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Refactor messages

export_test.go, restapi/api_test.go
Fix tests: exported symbols
Done on CI
=> Fix tests: exported symbols

doc/generate_class_diagram.sh, functional_tests.sh, run.sh, run_on_ci.sh, test.sh
Fixed shell issues
Run shellcheck to test.
=> Fixed shell issues

.travis.yml, Makefile, README.md, commands/help.go, shellcheck.sh
Incorporate `shellcheck` into CI
See on CI
=> Incorporate shellcheck into CI

export_test.go
Fixed `nolint` linter issue
N/A
=> Fixed `nolint` linter issue

ioc.go
Refactor: use expression list
Done on CI
=> Refactor: use expression list

commands/clusters.go, commands/configurations.go, commands/triggers.go, goconst.sh, restapi/api_impl.go
Fixed `goconst` issues
To be checked on CI.
=> Fixed `goconst` issues

restapi/api_impl.go
Fixed paths
To be checked on CI.
=> Fixed paths
