tests/functional_test.go

Output locally
```
$ go test ./tests -v
=== RUN   TestCheckQuitCommand
--- PASS: TestCheckQuitCommand (0.01s)
functional_test.go:53: CLI client has been started
functional_test.go:68: Expected output '> ' has been found
functional_test.go:82: Command 'quit' has been sent to CLI client
=== RUN   TestCheckVersionCommand
--- PASS: TestCheckVersionCommand (0.00s)
functional_test.go:53: CLI client has been started
functional_test.go:68: Expected output '> ' has been found
functional_test.go:82: Command 'version' has been sent to CLI client
functional_test.go:68: Expected output 'Insights operator CLI client' has been found
functional_test.go:68: Expected output 'version' has been found
functional_test.go:68: Expected output 'compiled' has been found
functional_test.go:68: Expected output '> ' …
```

make sure executable starts in the root of the project

---

tests/functional_test.go

This function is not used and is not a good pattern for testing (it's always better to wait for some event).

removed function pause

---

tests/functional_test.go

The test **fails** because provided clusterID is not used. Instead, it only gets incremented by 1, no matter what number is provided
```
> list clusters
List of clusters
0   11 fw0GEVCkhz
1   12 CFCxdn66vf
2   13 LqDxUOm4fJ
3   14 hNYI56SScu
4   15 NwqGPonapW
5   16 new
6   17 LQ9Yp32t26
7   18 WwJ9cERPM4
8   19 TF1eH0BUJL
9   20 nnqbUIJnL7
10   21 sXy8C9fbok
11   22 YTLXtGPlhW
12   23 6YBrDNyupr
13   24 FbP5s2moet
14   25 svMtzB2STY
15   26 Dxv8M3YWfc
16   27 XV42DbFauB
```
```
> add cluster 300 cluster
Controller has been registered
```
```
> list clusters
List of clusters
0   11 fw0GEVCkhz
1   12 CFCxdn66vf
2   13 LqDxUOm4fJ
3   14 hNYI56SScu
4   15 NwqGPonapW
5   16 new
6   17 LQ9Yp32t26
7   18 WwJ9cERPM4
8   19 TF1eH0BUJL
9   20 nnqbUIJnL7
10   21 sXy8C9fbok
11   22 YTLXtGPlhW
12 …
```

added TestAddClusterCommand

---

tests/functional_test.go

output locally
```
$ go test ./tests -v -run TestCheckQuitCommand
=== RUN   TestCheckQuitCommand
--- PASS: TestCheckQuitCommand (0.01s)
functional_test.go:55: CLI client has been started
functional_test.go:73: Expected output '> ' has been found
functional_test.go:87: Command 'quit' has been sent to CLI client
functional_test.go:55: CLI client has been started
functional_test.go:73: Expected output '> ' has been found
functional_test.go:87: Command 'exit' has been sent to CLI client
functional_test.go:55: CLI client has been started
functional_test.go:73: Expected output '> ' has been found
functional_test.go:87: Command 'bye' has been sent to CLI client
PASS
ok      github.com/redhatinsighs/insights-operator-cli/tests    0.017s
```

added more commands to test quit

---

functional_tests.sh

In order to be able to detect race conditions, we should enable `-race` for tests

Run functional tests with race option

---

commands/profiles.go
commands/profiles_test.go
ioc.go

Refactoring implementation of command 'delete profile' so it is possible to call it w/o confirmation.
Fixes #81 
This change is backed by new unit tests, so `./test.sh` is all what's needed ATM.

Fix issue 81

---

commands/configurations.go
commands/configurations_test.go
commands/rest_api_mock_test.go

Configuration is not stored when the file containing configuration can't be read for any reason.
Fixes #84
New unit tests are provided, so please use `./test.sh`

Configuration file read check

---

commands/clusters_test.go
commands/profiles.go
commands/profiles_test.go
commands/rest_api_mock_test.go

Unit tests for configuration profiles commands + bunch of other fixes.
Fixes #86
Updated code is covered by unit tests, so `./test.sh` is all what's needed ATM.

Profiles unit tests

---

restapi/api_test.go

Fixes #92
Please run `./test.sh` as usual.
```
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:33:          NewRestAPI                              100.0%
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:40:          ReadListOfClusters                      100.0%
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:60:          ReadListOfTriggers                      100.0%
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:79:          ReadTriggerByID                         100.0%
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:98:          ReadListOfConfigurationProfiles         100.0%
github.com/redhatinsighs/insights-operator-cli/restapi/api_impl.go:118:         ReadListOfConfigurations …
```

REST API tests v 4

---

restapi/api_test.go

Final version of REST API unit tests, with 100% code coverage
Fixes #92
Use `make test` as usual.
Expected coverage report:
```ok      github.com/redhatinsighs/insights-operator-cli  0.003s  coverage: 17.3% of statements
ok      github.com/redhatinsighs/insights-operator-cli/commands 0.009s  coverage: 73.2% of statements
ok      github.com/redhatinsighs/insights-operator-cli/restapi  0.043s  coverage: 100.0% of statements
ok      github.com/redhatinsighs/insights-operator-cli/types    0.010s  coverage: [no statements] [no tests to run]
```

Final version of rest api api

---

abcgo.sh

Don't use hardcoded color control chars in abcgo.sh
Fixes #162 

Don't use hardcoded color control chars in abcgo.sh

---

README.md

Link to GitHub pages as an badge icon

Link to GitHub pages as an badge icon

---

commands/copyright.go
docs/packages/commands/copyright.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/copyright.go`
Fixes #284
N/A

Fix issue #284

---

commands/rest_api_mock_test.go
docs/packages/commands/rest_api_mock_test.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/rest_api_mock_test.go`
Fixes #299
N/A

Fix issue 299

---

commands/rest_api_mock_empty_test.go
docs/packages/commands/rest_api_mock_empty_test.html

Add link to documentation generated for redhatinsights/insights-operator-cli/commands/rest_api_mock_empty_test.go
Fixes #297
N/A

Fix issue 297

---

commands/rest_api_mock_errors_test.go
docs/packages/commands/rest_api_mock_errors_test.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/rest_api_mock_errors_test.go`
Fixes #298
N/A

Fix issue 298

---

commands/clusters_test.go
docs/packages/commands/clusters_test.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/clusters_test.go`
Fixes #280
N/A

Fix issue 280

---

commands/copyright_test.go
docs/packages/commands/copyright_test.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/copyright_test.go`
Fixes #285
N/A

Fix issue 285

---

commands/authors_test.go
commands/clusters_test.go
commands/configurations_test.go
commands/copyright_test.go
commands/help_test.go
commands/license_test.go
commands/profiles_test.go
commands/rest_api_mock_empty_test.go
commands/rest_api_mock_errors_test.go
commands/rest_api_mock_test.go
commands/triggers_test.go

Links in comments should be placed after `package` clausule
Fixes #493
N/A

Links in comments should be placed after `package` clausule

---

commands/profiles.go
docs/packages/commands/profiles.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/profiles.go`
Fixes #295
N/A

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/profiles.go`

---

commands/commands.go
docs/packages/commands/commands.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/commands.go`
Fixes #281
N/A

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/commands.go`

---

commands/common_test.go
docs/packages/commands/common_test.html

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/common_test.go`
Fixes #288
N/A

 Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/common_test.go`

---

commands/commands_test.go

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/commands_test.go`
Fixes #286
N/A

Add link to documentation generated for `redhatinsights/insights-operator-cli/commands/commands_test.go`

---

docs/packages/ioc.html
ioc.go

Add link to documentation generated for `redhatinsights/insights-operator-cli/ioc.go`
Fixes #275
N/A

Add link to documentation generated for `redhatinsights/insights-operator-cli/ioc.go`

---

docs/packages/ioc_test.html
ioc_test.go

Add link to documentation `generated for redhatinsights/insights-operator-cli/ioc_test.go`
Fixes #276
N/A

Add link to documentation `generated for redhatinsights/insights-operator-cli/ioc_test.go`

---

docs/packages/export_test.html
export_test.go

Add link to documentation generated for `redhatinsights/insights-operator-cli/export_test.go`
Fixes #274
N/A

Add link to documentation generated for `redhatinsights/insights-operator-cli/export_test.go`

---

docs/packages/types/configuration_profile_test.html
types/configuration_profile_test.go

Add link to documentation generated for `types/configuration_profile_test.go`
Fixes #358
N/A

Fix issue #358

---

docs/packages/restapi/utils.html
restapi/utils.go

Fixes: the following string occured many times in sources: "Unable to read response body"
Fixes #145
N/A

Fixes: the following string occured many times in sources: "Unable to read response body"

---

docs/packages/restapi/utils.html
restapi/utils.go

Added link to generated documentation for `restapi/utils.go`
Fixes #386
N/A

Added link to generated documentation for `restapi/utils.go`

---

.travis.yml

Upgrading used version of Go from 1.14 to 1.16 in Travis CI.
Fixes #454 
No testing has been done.

Change Go version in CI from 1.14 to 1.16
